"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Bell, Boxes, CheckCircle2, ChevronDown, CircleHelp, ClipboardCheck, Download, Gauge, LayoutDashboard, Laptop, Menu, Plus, Search, Settings, UserPlus, Users, Wrench, X } from "lucide-react";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Status = "Assigned" | "Available" | "Repair";
type Asset = { id:string; name:string; type:string; assignee:string; location:string; status:Status; health:number };
type View = "Overview" | "Assets" | "People" | "Audits" | "Maintenance" | "Settings" | "Help centre";

const seedAssets: Asset[] = [
  { id:"LTP-0248", name:"MacBook Pro 14\"", type:"Laptop", assignee:"Amara Okafor", location:"Lagos HQ", status:"Assigned", health:94 },
  { id:"LTP-0182", name:"Dell Latitude 5420", type:"Laptop", assignee:"David Eze", location:"Abuja", status:"Assigned", health:81 },
  { id:"MON-0314", name:"Dell P2422H", type:"Monitor", assignee:"Unassigned", location:"Lagos Store", status:"Available", health:100 },
  { id:"PHN-0096", name:"Samsung Galaxy S23", type:"Phone", assignee:"Tomi Adebayo", location:"Remote", status:"Assigned", health:88 },
  { id:"LTP-0201", name:"HP EliteBook 840", type:"Laptop", assignee:"Maintenance", location:"Service centre", status:"Repair", health:42 },
  { id:"ACC-0447", name:"Logitech MX Keys", type:"Accessory", assignee:"Nneka Obi", location:"Lagos HQ", status:"Assigned", health:97 },
];
const people = [
  {name:"Amara Okafor",role:"Product Designer",location:"Lagos HQ",assets:3,initials:"AO"},
  {name:"David Eze",role:"Frontend Engineer",location:"Abuja",assets:2,initials:"DE"},
  {name:"Tomi Adebayo",role:"Account Manager",location:"Remote",assets:4,initials:"TA"},
  {name:"Nneka Obi",role:"Operations Lead",location:"Lagos HQ",assets:5,initials:"NO"},
  {name:"Chidi Nwosu",role:"Data Analyst",location:"Abuja",assets:2,initials:"CN"},
];
const activity = [{month:"Mar",assets:780},{month:"Apr",assets:835},{month:"May",assets:910},{month:"Jun",assets:982},{month:"Jul",assets:1108},{month:"Aug",assets:1194},{month:"Sep",assets:1284}];
const distribution = [{name:"Assigned",value:1036,color:"#59e1d9"},{name:"Available",value:196,color:"#c8ff36"},{name:"Repair",value:52,color:"#ffbd66"}];
const nav: {icon:typeof LayoutDashboard;label:View}[] = [{icon:LayoutDashboard,label:"Overview"},{icon:Boxes,label:"Assets"},{icon:Users,label:"People"},{icon:ClipboardCheck,label:"Audits"},{icon:Wrench,label:"Maintenance"}];
const viewCopy: Record<View,[string,string]> = {
  Overview:["Operations overview","Here’s what is happening across your asset inventory."],
  Assets:["Asset inventory","Search, filter and manage every registered device."],
  People:["People & assignments","See who has what and keep ownership records clear."],
  Audits:["Inventory audits","Plan checks and monitor reconciliation progress."],
  Maintenance:["Maintenance queue","Prioritise repairs and keep devices in service."],
  Settings:["Workspace settings","Manage notifications and inventory preferences."],
  "Help centre":["Help centre","Find quick guidance for common asset workflows."],
};

function AssetTable({assets,query,setQuery,status,setStatus,onSelect}:{assets:Asset[];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;onSelect:(a:Asset)=>void}) {
  const filtered=useMemo(()=>assets.filter(a=>(status==="All status"||a.status===status)&&`${a.id} ${a.name} ${a.assignee}`.toLowerCase().includes(query.toLowerCase())),[assets,query,status]);
  return <section className="dash-card assets-card"><div className="card-heading assets-heading"><div><h2>Asset inventory</h2><p>{filtered.length} records shown</p></div><div className="table-tools"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets..."/></label><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by status"><option>All status</option><option>Assigned</option><option>Available</option><option>Repair</option></select></div></div>
    <Table><TableHeader><TableRow><TableHead>Asset</TableHead><TableHead>Assigned to</TableHead><TableHead>Location</TableHead><TableHead>Status</TableHead><TableHead>Health</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{filtered.map(asset=><TableRow key={asset.id}><TableCell><div className="asset-name"><span><Laptop size={16}/></span><div><b>{asset.name}</b><small>{asset.id} · {asset.type}</small></div></div></TableCell><TableCell>{asset.assignee}</TableCell><TableCell>{asset.location}</TableCell><TableCell><span className={`status-badge ${asset.status.toLowerCase()}`}><i/>{asset.status}</span></TableCell><TableCell><div className="health-cell"><span>{asset.health}%</span><i><b style={{width:`${asset.health}%`}}/></i></div></TableCell><TableCell><button className="row-action" onClick={()=>onSelect(asset)} aria-label={`View ${asset.name}`}>View</button></TableCell></TableRow>)}</TableBody></Table>
    {filtered.length===0&&<div className="empty-state"><Search/><b>No matching assets</b><span>Try a different search or status.</span></div>}
  </section>;
}

function Overview({assets,query,setQuery,status,setStatus,onSelect,range,setRange}:{assets:Asset[];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;onSelect:(a:Asset)=>void;range:string;setRange:(v:string)=>void}) {
  return <>
    <section className="stat-grid" aria-label="Asset statistics"><article><div className="stat-top"><span className="stat-icon aqua"><Boxes size={19}/></span><em>+8.2%</em></div><small>Total assets</small><strong>1,284</strong><p>97 added this quarter</p></article><article><div className="stat-top"><span className="stat-icon lime"><Users size={19}/></span><em>80.7%</em></div><small>Assigned</small><strong>1,036</strong><p>Across 624 employees</p></article><article><div className="stat-top"><span className="stat-icon yellow"><Wrench size={19}/></span><em className="neutral">12 open</em></div><small>In maintenance</small><strong>52</strong><p>7 overdue actions</p></article><article><div className="stat-top"><span className="stat-icon violet"><Gauge size={19}/></span><em>+1.4%</em></div><small>Inventory health</small><strong>96.4%</strong><Progress value={96.4} className="health-progress"/></article></section>
    <section className="analytics-grid"><article className="dash-card chart-card"><div className="card-heading"><div><h2>Asset growth</h2><p>Total registered assets over time</p></div><select className="chart-select" value={range} onChange={e=>setRange(e.target.value)}><option>Last 7 months</option><option>Last quarter</option><option>This year</option></select></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activity} margin={{left:-25,right:5,top:15}}><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2bbeb6" stopOpacity={.26}/><stop offset="100%" stopColor="#2bbeb6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e4ebed"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"#809097",fontSize:11}}/><Tooltip contentStyle={{borderRadius:10,border:"1px solid #dbe4e8",fontSize:12}}/><Area type="monotone" dataKey="assets" stroke="#168e88" strokeWidth={2.5} fill="url(#areaFill)"/></AreaChart></ResponsiveContainer></div></article>
    <article className="dash-card distribution-card"><div className="card-heading"><div><h2>Asset distribution</h2><p>Current lifecycle status</p></div></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" innerRadius={55} outerRadius={75} paddingAngle={4}>{distribution.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{fontSize:12,borderRadius:9}}/></PieChart></ResponsiveContainer><div className="donut-total"><strong>1,284</strong><span>Total</span></div></div><div className="legend">{distribution.map(item=><div key={item.name}><i style={{background:item.color}}/><span>{item.name}</span><b>{item.value}</b></div>)}</div></article></section>
    <AssetTable {...{assets,query,setQuery,status,setStatus,onSelect}}/>
  </>;
}

function PeopleView({onInvite}:{onInvite:()=>void}) { return <><section className="mini-stat-row"><article><span>Team members</span><strong>624</strong></article><article><span>With assigned assets</span><strong>586</strong></article><article><span>Remote custodians</span><strong>142</strong></article></section><section className="dash-card simple-view"><div className="card-heading"><div><h2>Directory</h2><p>Active employees with asset records</p></div><button className="primary-action" onClick={onInvite}><UserPlus size={15}/>Add person</button></div><div className="people-list">{people.map(person=><article key={person.name}><span className="person-avatar">{person.initials}</span><div><b>{person.name}</b><small>{person.role}</small></div><span>{person.location}</span><em>{person.assets} assets</em><button>View profile</button></article>)}</div></section></>; }

function AuditsView({notice}:{notice:(s:string)=>void}) { const audits=[{name:"Q3 laptop verification",progress:76,due:"Due 18 Sep",scope:"328 devices"},{name:"Lagos office accessories",progress:42,due:"Due 25 Sep",scope:"184 items"},{name:"Remote employee check",progress:100,due:"Completed",scope:"96 devices"}]; return <section className="view-grid">{audits.map(a=><article className="dash-card audit-card" key={a.name}><div className="audit-icon"><ClipboardCheck/></div><span>{a.due}</span><h2>{a.name}</h2><p>{a.scope}</p><Progress value={a.progress}/><div><b>{a.progress}% reconciled</b><button onClick={()=>notice(a.progress===100?"Audit report downloaded":"Audit workspace opened")}>{a.progress===100?"Download report":"Continue audit"}</button></div></article>)}<button className="new-view-card" onClick={()=>notice("New audit draft created")}><Plus/>Create a new audit</button></section>; }

function MaintenanceView({notice}:{notice:(s:string)=>void}) { const jobs=[{asset:"HP EliteBook 840",issue:"Battery health below threshold",priority:"High",age:"4 days"},{asset:"Dell Latitude 7410",issue:"Keyboard replacement",priority:"Medium",age:"2 days"},{asset:"iPhone 13",issue:"Screen damage assessment",priority:"High",age:"1 day"},{asset:"Dell P2422H",issue:"Display flicker",priority:"Low",age:"Today"}]; return <section className="dash-card simple-view"><div className="card-heading"><div><h2>Open service requests</h2><p>4 of 12 active requests shown</p></div><button className="primary-action" onClick={()=>notice("Service request form opened")}>New request</button></div><div className="maintenance-list">{jobs.map(job=><article key={job.asset}><span className={`priority ${job.priority.toLowerCase()}`}>{job.priority}</span><div><b>{job.asset}</b><small>{job.issue}</small></div><span>{job.age}</span><button onClick={()=>notice(`${job.asset} marked as in progress`)}>Start work</button></article>)}</div></section>; }

function SettingsView({notice}:{notice:(s:string)=>void}) { return <section className="settings-layout"><article className="dash-card settings-card"><h2>Inventory preferences</h2><p>Choose how TrackForge handles alerts and asset records.</p>{[["Warranty alerts","Notify administrators 30 days before warranty expiry"],["Maintenance reminders","Send a reminder when service tasks become overdue"],["Weekly inventory digest","Email a summary every Monday morning"]].map(([a,b],i)=><label key={a}><div><b>{a}</b><small>{b}</small></div><input type="checkbox" defaultChecked={i<2}/><span/></label>)}<button className="primary-action" onClick={()=>notice("Settings saved successfully")}>Save changes</button></article><article className="dash-card settings-card"><h2>Workspace details</h2><label className="field-label">Workspace name<input defaultValue="Westbridge Ops"/></label><label className="field-label">Default location<select defaultValue="Lagos HQ"><option>Lagos HQ</option><option>Abuja</option><option>Remote</option></select></label><button className="outline-action" onClick={()=>notice("Workspace details updated")}>Update workspace</button></article></section>; }

function HelpView({notice}:{notice:(s:string)=>void}) { return <><section className="help-search"><Search/><input placeholder="Search help articles..." onKeyDown={e=>{if(e.key==="Enter")notice("Showing help results")}}/></section><section className="view-grid help-grid">{[["Registering assets","Add devices individually or prepare a bulk import."],["Managing assignments","Assign, transfer and recover employee equipment."],["Running an audit","Verify inventory and resolve missing records."],["Maintenance workflows","Create service requests and monitor repairs."]].map(([a,b])=><button className="dash-card help-card" key={a} onClick={()=>notice(`${a} guide opened`)}><CircleHelp/><b>{a}</b><span>{b}</span></button>)}</section></>; }

export default function Dashboard() {
  const [assets,setAssets]=useState(seedAssets); const [query,setQuery]=useState(""); const [status,setStatus]=useState("All status"); const [open,setOpen]=useState(false); const [active,setActive]=useState<View>("Overview"); const [mobileOpen,setMobileOpen]=useState(false); const [notice,setNotice]=useState(""); const [notifications,setNotifications]=useState(false); const [workspaceMenu,setWorkspaceMenu]=useState(false); const [profileMenu,setProfileMenu]=useState(false); const [selected,setSelected]=useState<Asset|null>(null); const [range,setRange]=useState("Last 7 months"); const searchRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),2800);return()=>clearTimeout(timer)},[notice]);
  function selectView(view:View){setActive(view);setMobileOpen(false);if(view!=="Assets")setQuery("");}
  function addAsset(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setAssets(current=>[{id:`LTP-${String(300+current.length)}`,name:String(data.get("name")),type:String(data.get("type")),assignee:"Unassigned",location:String(data.get("location")),status:"Available",health:100},...current]);setOpen(false);setNotice("Asset registered successfully");setActive("Assets");}
  function exportCsv(){const rows=[["ID","Name","Type","Assignee","Location","Status","Health"],...assets.map(a=>[a.id,a.name,a.type,a.assignee,a.location,a.status,String(a.health)])];const blob=new Blob([rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="trackforge-assets.csv";a.click();URL.revokeObjectURL(url);setNotice("CSV export downloaded");}
  const [title,description]=viewCopy[active];
  return <main className="dashboard-shell">
    {mobileOpen&&<button className="sidebar-backdrop" aria-label="Close menu" onClick={()=>setMobileOpen(false)}/>}<aside className={`dash-sidebar ${mobileOpen?"mobile-open":""}`}><button className="close-sidebar" onClick={()=>setMobileOpen(false)}><X/></button><Link className="dash-brand" href="/"><span className="brand-mark">TF</span><span>TrackForge</span></Link><button className="workspace-switch" onClick={()=>setWorkspaceMenu(v=>!v)}><span>WO</span><div><small>Workspace</small><b>Westbridge Ops</b></div><ChevronDown size={15}/></button>{workspaceMenu&&<div className="side-popover"><button onClick={()=>{setWorkspaceMenu(false);setNotice("Personal workspace selected")}}>Personal workspace</button><button onClick={()=>setNotice("New workspace setup opened")}>+ Create workspace</button></div>}<nav aria-label="Dashboard navigation"><small className="nav-label">Workspace</small>{nav.map(({icon:Icon,label})=><button key={label} onClick={()=>selectView(label)} className={active===label?"active":""}><Icon size={18}/><span>{label}</span>{label==="Maintenance"&&<em>7</em>}</button>)}</nav><div className="sidebar-bottom"><button className={active==="Help centre"?"active":""} onClick={()=>selectView("Help centre")}><CircleHelp size={18}/>Help centre</button><button className={active==="Settings"?"active":""} onClick={()=>selectView("Settings")}><Settings size={18}/>Settings</button><button className="profile" onClick={()=>setProfileMenu(v=>!v)}><span>WD</span><div><b>Wisdom Dickson</b><small>Asset administrator</small></div><ChevronDown size={14}/></button>{profileMenu&&<div className="side-popover profile-popover"><button onClick={()=>setNotice("Profile opened")}>View profile</button><Link href="/">Sign out of demo</Link></div>}</div></aside>
    <section className="dash-main"><header className="dash-header"><button className="mobile-dash-menu" aria-label="Open menu" onClick={()=>setMobileOpen(true)}><Menu/></button><div className="global-search"><Search size={17}/><input ref={searchRef} value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value)setActive("Assets")}} aria-label="Search everything" placeholder="Search assets, people or IDs..."/><kbd>⌘ K</kbd></div><div className="header-actions"><div className="notification-wrap"><button aria-label="Notifications" className="icon-button" onClick={()=>setNotifications(v=>!v)}><Bell size={18}/><i/></button>{notifications&&<div className="notification-panel"><b>Notifications</b><button onClick={()=>{setNotifications(false);setActive("Maintenance")}}>7 maintenance actions are overdue <span>View queue</span></button><button onClick={()=>{setNotifications(false);setActive("Audits")}}>Q3 audit is 76% complete <span>Continue</span></button></div>}</div><span className="sync-status"><i/> Inventory synced</span></div></header>
      <div className="dash-content">{notice&&<div className="action-toast"><CheckCircle2/>{notice}</div>}<div className="page-title"><div><span>Friday, 5 September</span><h1>{title}</h1><p>{description}</p></div><div className="title-actions">{(active==="Overview"||active==="Assets")&&<button className="outline-action" onClick={exportCsv}><Download size={16}/>Export</button>}<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button className="primary-action"><Plus size={17}/>Add asset</button></DialogTrigger><DialogContent className="asset-dialog"><DialogHeader><DialogTitle>Register a new asset</DialogTitle><DialogDescription>Add the essential details. The asset will begin as available.</DialogDescription></DialogHeader><form onSubmit={addAsset}><label>Asset name<input name="name" required placeholder="e.g. Lenovo ThinkPad X1"/></label><div className="form-row"><label>Category<select name="type"><option>Laptop</option><option>Monitor</option><option>Phone</option><option>Accessory</option></select></label><label>Location<select name="location"><option>Lagos HQ</option><option>Abuja</option><option>Remote</option><option>Lagos Store</option></select></label></div><DialogFooter><DialogClose asChild><button type="button" className="outline-action">Cancel</button></DialogClose><button className="primary-action" type="submit">Register asset</button></DialogFooter></form></DialogContent></Dialog></div></div>
        {active==="Overview"&&<Overview {...{assets,query,setQuery,status,setStatus,range,setRange}} onSelect={setSelected}/>} {active==="Assets"&&<AssetTable {...{assets,query,setQuery,status,setStatus}} onSelect={setSelected}/>} {active==="People"&&<PeopleView onInvite={()=>setNotice("Invitation form opened")}/>} {active==="Audits"&&<AuditsView notice={setNotice}/>} {active==="Maintenance"&&<MaintenanceView notice={setNotice}/>} {active==="Settings"&&<SettingsView notice={setNotice}/>} {active==="Help centre"&&<HelpView notice={setNotice}/>} 
      </div>
    </section>
    <Dialog open={!!selected} onOpenChange={value=>{if(!value)setSelected(null)}}><DialogContent className="asset-dialog">{selected&&<><DialogHeader><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.id} · {selected.type}</DialogDescription></DialogHeader><div className="asset-details"><div><span>Assigned to</span><b>{selected.assignee}</b></div><div><span>Location</span><b>{selected.location}</b></div><div><span>Status</span><b>{selected.status}</b></div><div><span>Health</span><b>{selected.health}%</b></div></div><DialogFooter><DialogClose asChild><button className="outline-action">Close</button></DialogClose><button className="primary-action" onClick={()=>{setSelected(null);setNotice("Asset edit form opened")}}>Edit asset</button></DialogFooter></>}</DialogContent></Dialog>
  </main>;
}
